### ISSUE TITLE
fix incorrect (404) link to spec in help text

### ISSUE THREAD

**Issue by jf** [riemann/riemann-dash#118] opened 2016-05-18 01:11 UTC
I'm thinking the following:

`https://github.com/aphyr/riemann/blob/master/src/riemann/Query.g` should now be `https://github.com/riemann/riemann/blob/master/resources/query.g4` in `lib/riemann/dash/public/views/help.js` ?

**Comment by mfournier** [comment] 2016-05-18 12:07
This a duplicate of #108, fixed in #109 but not part of any release yet.

**Closed by mfournier** 2016-05-18 12:07 UTC
